### ISSUE TITLE
Ask for your final train model weight of  Yolo V3 Eye Detection

### ISSUE THREAD

**Issue by yejg2017** [rcdilorenzo/inspector-lestrade#1]
Thankds for you share code,and could you share you final train weight for me ?I do not have GPU and it is difficult to train for me .

**Comment by rcdilorenzo** [comment]
Checkout the releases page. The weights should be available from there.

https://github.com/rcdilorenzo/inspector-lestrade/releases

--

Christian Di Lorenzo
